/* Automatically generated by './build/bin/build-entry.js' */
const { version } = require("../package.json");
import Pagination from "./components/pagination";
import Dialog from "./components/dialog";
import Autocomplete from "./components/autocomplete";
import Dropdown from "./components/dropdown";
import DropdownMenu from "./components/dropdown-menu";
import DropdownItem from "./components/dropdown-item";
import Menu from "./components/menu";
import Submenu from "./components/submenu";
import MenuItem from "./components/menu-item";
import MenuItemGroup from "./components/menu-item-group";
import Input from "./components/input";
import InputNumber from "./components/input-number";
import Radio from "./components/radio";
import RadioGroup from "./components/radio-group";
import RadioButton from "./components/radio-button";
import Checkbox from "./components/checkbox";
import CheckboxButton from "./components/checkbox-button";
import CheckboxGroup from "./components/checkbox-group";
import Switch from "./components/switch";
import Select from "./components/select";
import Option from "./components/option";
import OptionGroup from "./components/option-group";
import Button from "./components/button";
import ButtonGroup from "./components/button-group";
import Table from "./components/table";
import TableColumn from "./components/table-column";
import DatePicker from "./components/date-picker";
import TimeSelect from "./components/time-select";
import TimePicker from "./components/time-picker";
import Popover from "./components/popover";
import Tooltip from "./components/tooltip";
import MessageBox from "./components/message-box";
import Breadcrumb from "./components/breadcrumb";
import BreadcrumbItem from "./components/breadcrumb-item";
import Form from "./components/form";
import FormItem from "./components/form-item";
import Tabs from "./components/tabs";
import TabPane from "./components/tab-pane";
import Tag from "./components/tag";
import Tree from "./components/tree";
import Alert from "./components/alert";
import Notification from "./components/notification";
import Slider from "./components/slider";
import Loading from "./components/loading";
import Icon from "./components/icon";
import Row from "./components/row";
import Col from "./components/col";
import Upload from "./components/upload";
import Progress from "./components/progress";
import Spinner from "./components/spinner";
import Message from "./components/message";
import Badge from "./components/badge";
import Card from "./components/card";
import Rate from "./components/rate";
import Steps from "./components/steps";
import Step from "./components/step";
import Carousel from "./components/carousel";
import Scrollbar from "./components/scrollbar";
import CarouselItem from "./components/carousel-item";
import Collapse from "./components/collapse";
import CollapseItem from "./components/collapse-item";
import Cascader from "./components/cascader";
import ColorPicker from "./components/color-picker";
import Transfer from "./components/transfer";
import Container from "./components/container";
import Header from "./components/header";
import Aside from "./components/aside";
import Main from "./components/main";
import Footer from "./components/footer";
import Timeline from "./components/timeline";
import TimelineItem from "./components/timeline-item";
import Link from "./components/link";
import Divider from "./components/divider";
import Image from "./components/image";
import Calendar from "./components/calendar";
import Backtop from "./components/backtop";
import InfiniteScroll from "./components/infinite-scroll";
import PageHeader from "./components/page-header";
import CascaderPanel from "./components/cascader-panel";
import Avatar from "./components/avatar";
import Drawer from "./components/drawer";
import Popconfirm from "./components/popconfirm";
import Skeleton from "./components/skeleton";
import SkeletonItem from "./components/skeleton-item";
import Empty from "./components/empty";
import locale from "./locale";
import CollapseTransition from "./transitions/collapse-transition";

const components = [
  Pagination,
  Dialog,
  Autocomplete,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Menu,
  Submenu,
  MenuItem,
  MenuItemGroup,
  Input,
  InputNumber,
  Radio,
  RadioGroup,
  RadioButton,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Switch,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Table,
  TableColumn,
  DatePicker,
  TimeSelect,
  TimePicker,
  Popover,
  Tooltip,
  Breadcrumb,
  BreadcrumbItem,
  Form,
  FormItem,
  Tabs,
  TabPane,
  Tag,
  Tree,
  Alert,
  Slider,
  Icon,
  Row,
  Col,
  Upload,
  Progress,
  Spinner,
  Badge,
  Card,
  Rate,
  Steps,
  Step,
  Carousel,
  Scrollbar,
  CarouselItem,
  Collapse,
  CollapseItem,
  Cascader,
  ColorPicker,
  Transfer,
  Container,
  Header,
  Aside,
  Main,
  Footer,
  Timeline,
  TimelineItem,
  Link,
  Divider,
  Image,
  Calendar,
  Backtop,
  PageHeader,
  CascaderPanel,
  Avatar,
  Drawer,
  Popconfirm,
  Skeleton,
  SkeletonItem,
  Empty,
  CollapseTransition,
];

const install = function (Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach((component) => {
    Vue.component(component.name, component);
  });

  Vue.use(InfiniteScroll);
  Vue.use(Loading.directive);

  Vue.prototype.$ELEMENT = {
    size: opts.size || "",
    zIndex: opts.zIndex || 2000,
  };

  Vue.prototype.$loading = Loading.service;
  Vue.prototype.$msgbox = MessageBox;
  Vue.prototype.$alert = MessageBox.alert;
  Vue.prototype.$confirm = MessageBox.confirm;
  Vue.prototype.$prompt = MessageBox.prompt;
  Vue.prototype.$notify = Notification;
  Vue.prototype.$message = Message;
};

/* 检测到 Vue 才执行 */
if (typeof window !== "undefined" && window.Vue) {
  install(window.Vue);
}

export default {
  version,
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Loading,
  Pagination,
  Dialog,
  Autocomplete,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Menu,
  Submenu,
  MenuItem,
  MenuItemGroup,
  Input,
  InputNumber,
  Radio,
  RadioGroup,
  RadioButton,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Switch,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Table,
  TableColumn,
  DatePicker,
  TimeSelect,
  TimePicker,
  Popover,
  Tooltip,
  MessageBox,
  Breadcrumb,
  BreadcrumbItem,
  Form,
  FormItem,
  Tabs,
  TabPane,
  Tag,
  Tree,
  Alert,
  Notification,
  Slider,
  Icon,
  Row,
  Col,
  Upload,
  Progress,
  Spinner,
  Message,
  Badge,
  Card,
  Rate,
  Steps,
  Step,
  Carousel,
  Scrollbar,
  CarouselItem,
  Collapse,
  CollapseItem,
  Cascader,
  ColorPicker,
  Transfer,
  Container,
  Header,
  Aside,
  Main,
  Footer,
  Timeline,
  TimelineItem,
  Link,
  Divider,
  Image,
  Calendar,
  Backtop,
  InfiniteScroll,
  PageHeader,
  CascaderPanel,
  Avatar,
  Drawer,
  Popconfirm,
  Skeleton,
  SkeletonItem,
  Empty,
};
